baseurl = "/"
title = "Jack's Blog"
author = "Jack"
relativeurls = true
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Jack's Random Thoughts"

[[menu.main]]
    name = "Home"
    url = "https://jacksblog.netlify.com"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Jhumbl"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com"
    weight = 3
[[menu.main]]
    name = "Kaggle"
    url = "https://www.kaggle.com/jumble"
    weight = 4
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com"
    weight = 5
[[menu.main]]
    name = "CUSP"
    url = "https://cusplondon.ac.uk"
    weight = 6
