---
title: Visualising Algorithms - DBSCAN/OPTICS
author: Jack Humble
date: '2019-08-15'
slug: visualising-algorithms
categories: []
tags: []
---
<!--html_preserve-->
<link rel="stylesheet" type="text/css" href="/post/2019-08-15-visualising-algorithms-files/style.css">
<script type="text/javascript" src="/post/2019-08-15-visualising-algorithms-files/OPTICS_algorithm.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/d3js/5.15.0/d3.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!--/html_preserve-->

## DBSCAN/OPTICS

*Density-based spatial clustering of applications with noise* (**DBSCAN**)<sup>1</sup> is an incredibly powerful and popular data mining technique for unsupervised learning. It is able to detect clusters based on their density without having to specify the number of clusters we want. The main drawbacks, however, are its highly sensitive dependancy on the initial parameters (*𝜀* and *MinPts*) as well as its inability to detect clusters of varying density. An extension to DBSCAN aimed at mitigating these drawbacks in an algorithm known as *Ordering Points to Identify the Clustering Structure* (**OPTICS**)<sup>2</sup>. The visualisation below shows how we can identify clusters of different densities and see the clustering structure across the entire range of the epsilon parameter, giving us a much deeper understanding of the underlying data. 
Move your mouse across the bar chart at the bottom to see how the 𝜀-epsilon parameter affects the clusters that are identified.
<br>

<div id="chart" align="center" style="width:700px; height:900px; margin:auto;">
  <button id="algorithm-button">Click to run OPTICS algorithm!</button>
</div>

<script type="text/javascript" src="/post/2019-08-15-visualising-algorithms-files/d3_app.js"></script>
<script type="text/javascript" src="/post/2019-08-15-visualising-algorithms-files/jquery-csv.js"></script>

<br></br>




<h2>D3.js</h2>
This visualisation was created with D3.js (Data Driven Documents), a javascript library allowing developers to bind data to elements of the document object model and draw svg elements whose attributes are determined by the underlying data. More information can be found at [https://d3js.org/](https://d3js.org/).

<h3>References</h3>
1. Ester M., Kriegel H.-P., Sander J., Xu X.: “A Density Based Algorithm for Discovering Clusters in Large Spatial Databases with Noise”, Proc. 2nd Int. Conf. on Knowledge Discovery and Data Mining, Portland, OR, AAAI Press, **1996**, pp. 226-231.
2. M. Ankerst, M. M. Breunig, H.-P. Kriegel, and J. Sander. “OPTICS: Ordering Points To Identify the Clustering Structure”. In: Proc. SIGMOD. **1999**, pp. 49–60

